### ISSUE TITLE
How to guarantee that the model has access to the whole motion sequence?

### ISSUE THREAD

**Issue by nkueng** [eth-ait/dip18#12]
Dear DIP authors,

I am working on a re-implementation of your impressive paper. However, I am struggling when it comes to replicating your data feeding strategy during training.

Quoting from the paper: 

> At training-time our network has access to the whole sequence [...]

I am wondering how your implementation adheres to this. For training, you use a `batch_size` of 16 samples for a dataset of motion sequences (of varying length) split up into samples of 300 frames.

Since there are sequences in your dataset of more than 4800 frames (16 samples * 300 frames/sample) which do not fit into a single batch, how do you guarantee that the model has access to the whole motion sequence?

I tried to answer this question from your implementation but didn't find what I was looking for.

Thank you very much for your time!

**Comment by kaufManu** [comment]
Dear Nicola,

We actually pre-processed the data so that the training set contains sequences of minimum 10 and maximum 300 frames. If a training sequence is bigger than 300, we simply split it up. Sequences that are between 10 and 300 frames are padded dynamically during training time. That's unfortunately not something that is documented in the code base, so apologies for that!

Does that answer your question?

**Comment by nkueng** [comment]
Hi Manuel,

Thanks a bunch for reaching out so quickly!

I guess you answered my question implicitly, so just to make sure: 
Your data processing **cannot** guarantee, that the model has access to the whole sequence if the sequence doesn't fit into a single batch?

Now, that I already got you started, I hope you don't mind another question:
How do you handle the case, where a batch is composed of different sequences (e.g., from different subjects): Do you re-initialize the hidden state of the LSTM cells whenever a new sequence is fed to the model?

Many thanks for your time and sorry for the nuisance!

Cheers,
Nicola

**Comment by kaufManu** [comment]
Yes, that is correct, if a sequence does not fit into a single batch, our model won't see the entire sequence. Just to be clear: This only matters for the offline evaluations - in the online evaluations we are using a windowed approach anyway.

I'm not sure I fully understand the second question. If the batch size is bigger than 1, the different sequences can come from different subjects (that is quite likely in fact, since AMASS has many subjects).  However, keep in mind that DIP does not estimate the shape of a subject, i.e. we always use the mean shape, hence we actually only have a single subject. The hidden states are reset whenever we start processing a batch, i.e. they are reset for all sequences in the batch.

Hope that helps!

**Comment by nkueng** [comment]
> Just to be clear: This only matters for the offline evaluations - in the online evaluations we are using a windowed approach anyway.

Absolutely! I was really just confused how to implement that "the model has access to the whole sequence" when the sequences wouldn't fit in a batch...

> I'm not sure I fully understand the second question.

I think you answered it partly :) I am not referring to the SMPL _shape_ parameters, but only to the mapping from IMU data to SMPL _pose_ parameters learnt by the model. If we didn't re-initialize the hidden state between passing different sequences, the model would wrongly assume, that all the motion data belongs to one single sequence (with big jumps where the source sequences were collated), right?

Once again many thanks for your support!

**Comment by kaufManu** [comment]
> If we didn't re-initialize the hidden state between passing different sequences, the model would wrongly assume, that all the motion data belongs to one single sequence (with big jumps where the source sequences were collated), right?

Ah, now I see - yes that is absolutely correct.

Glad I could help and good luck with your projects!

Best,
Manuel
