### ISSUE TITLE
Question: Super Noisy Acceleration Data?

### ISSUE THREAD

**Issue by jyf588** [eth-ait/dip18#19]
Hi!

Thank you so much for creating this really useful IMU dataset. I encountered a problem when I was playing around with it and was wondering if you could kindly help me with it:

When I load the raw IMU data, select a random sensor, and visualize its readings, the IMU orientations look pretty much reasonable and consistent, but the acceleration visualizations (direction of plotted 3D vectors) almost look white noise to me as they wildly change directions every timestep. 

Is this something you would expect or I must be doing something wrong? How could I convince myself (e.g. through visualization code) that I am using the IMU acc readings correctly?

Thanks!

**Comment by xdtcssdi** [comment]
HI, Can we communicate the generation of Transpose dataset.

**Comment by kaufManu** [comment]
Hi,

@jyf588 It is normal that accelerations look noisy. It is also not so easy to interpret them visually because you might feel like they behave counter-intuitively (e.g. when an arm is moving upward, but it is slowing down, then the acceleration will point in the opposite direction of movement). Also make sure that the accelerations you are looking at do not contain the gravity component.

One way of sanity-checking the accelerations is to synthesize them via finite differences by using a vertex on the SMPL mesh and then checking whether those synthetic accelerations match the real ones. A perfect match is unlikely, but at least it should give you a rough idea. With some smoothing to remove the noise you should get a reasonable match.

As @xdtcssdi mentions, feel free to take a look at their repository (https://github.com/Xinyu-Yi/TransPose) which might be helpful, too.

Best regards
Manuel
