### ISSUE TITLE
Datasets and configuration

### ISSUE THREAD

**Issue by whl-007** [eth-ait/dip18#31]
I'm currently replicating your work DIP and I found that the tensorflow version you provided is no longer available. I'm using Python 3.8.15 and I also need opencv, numpy-quaternion, and numba libraries. Can I successfully reproduce your DIP implementation with your codebase? 
Besides, I have a question regarding the data_synthesis folder. In the md file, it says to download MoCap sequences from [AMASS](https://amass.is.tue.mpg.de/), and the code here uses a sample sequence from HumanEva. However, I noticed that there are two MoCap datasets in AMASS: TCDHands (TCD_handMocap) and Transitions (Transitions_mocap). I am unsure which one to download, and I also don't know where to place the dataset as there are no corresponding path variables in the .py files. 
Also, what does "The code here uses a sample sequence from HumanEva" mean? Does it imply that I need to download the HumanEva dataset? 
As a non-native speaker of English and a novice undergraduate student, I am sorry for my lack of understanding and I hope you will not be angry with me for asking such simple and foolish questions. Thank you very sincerely.

**Comment by kaufManu** [comment]
Hi, no bad questions here, so no worries.

- In theory, the work should still be reproducible with the libraries you mention. AFAIK, the newest versions of those libraries should support all features that you need. You might want to reach out to the authors of a follow-up work of DIP, e.g. [PIP](https://github.com/Xinyu-Yi/PIP) - may be they already have a re-implementation of DIP with the newest libraries.
- AMASS contains many datasets and since publication of DIP it has grown. If you want to re-train from scratch, I think it makes sense to train on the newest version of AMASS (i.e. all the data it provides). If you want to specifically traing like DIP did at the time, we also release the version of AMASS that we used at the time on our [Download page](https://dip.is.tue.mpg.de/download.php).
- _The code here uses a sample sequence from HumanEva_ means that a sequence taken from HumanEva is provided as an example, so no need to download it. You find that sequence directly in the repository ([here](https://github.com/eth-ait/dip18/blob/master/data_synthesis/Jog_1.pkl)). I.e., if you clone the repo and run [`run_demo.sh`](https://github.com/eth-ait/dip18/blob/master/data_synthesis/run_demo.sh), it should work as is.

**Comment by whl-007** [comment]
Dear kaufManu, thank you for your help. I will try again based on what you said. If there are still problems, I may try to reproduce PIP. Thank you very much for your guidance.
